name: university_management
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  dio: ^5.4.2+1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_vector_icons: ^2.0.0
  font_awesome_flutter: ^10.7.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  provider: ^6.1.2
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/masks/
    - assets/images/logo/
    - assets/images/icons/
    - assets/images/

  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Regular.ttf
